# TUTORIAL 3 : Evolute of curves

The evolute of a curve is by definition the set of its centers of curvatures. The goal of this lab session is to define a generic function that computes the evolute of any parameterized curve. 

## PART I. 
We assume in the following that we have a parametrized curve $f:[a,b]\to\mathbb{R}^3$ which is only known through a discretization $(t,f)$ where $$\textit{t = np.linspace(0,1,n)}\quad f=(f(t_0),\cdots,f(t_{n-1})).$$
$f$ is therefore of size $3 \times n$.

## 1) Discrete derivative
Define a function that calculate an approximation of the derivative of $f$. The output has the same size than $t$ and $f$. 

In [17]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

#----------------------
# discrete derivature
def derivative(t,f):
    deriv_f = np.zeros(f.shape)
    for i in range(len(t)-1):
        deriv_f[:,i] = (f[:,i]-f[:,i+1])/(t[i]-t[i+1])
    deriv_f[:,len(t)-1] = (f[:,len(t)-2]-f[:,len(t)-1])/(t[len(t)-2]-t[len(t)-1])
    return deriv_f

#---------------------
# check that function on simple examples

t = np.linspace(0,1,5)
f = lambda x : 2*x
F = np.array([f(t), f(t), f(t)])

derivative(t, F)


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## 2) Discrete normal vector
The goal is to build the function that outputs for every $t_i$ the unit normal $N(t_i)$.

In [26]:
#----------------------
# discrete derivature
def normal_vector(t,f):
    n = len(t)
    tangent_f = np.zeros((3,n))
    df = derivative(t,f)
    for i in range(n) :
        tangent_f[:,i] = df[:,i] / np.linalg.norm(df[:,i],2)
    print(tangent_f)
    normal_f = derivative(t, tangent_f)
    print(normal_f)
    for i in range(n) :
        if np.linalg.norm(normal_f[:,i], 2) :
            normal_f[:,i] = normal_f[:,i] / np.linalg.norm(normal_f[:,i], 2)
    return normal_f # normal_f is of size 3 x n

#---------------------
# check that function on simple examples
F = np.array([np.cos(t), np.sin(t), t])
normal_vector(t, F)

[[-0.08804343 -0.25865616 -0.41318691 -0.5420277  -0.5420277 ]
 [ 0.7006751   0.65711052  0.57268998  0.45266236  0.45266236]
 [ 0.70802737  0.70802737  0.70802737  0.70802737  0.70802737]]
[[-0.68245095 -0.618123   -0.51536315 -0.         -0.        ]
 [-0.17425834 -0.33768213 -0.48011049 -0.         -0.        ]
 [-0.         -0.         -0.         -0.         -0.        ]]


array([[-0.96891242, -0.87758256, -0.73168887, -0.        , -0.        ],
       [-0.24740396, -0.47942554, -0.68163876, -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        , -0.        ]])

## 3) Curvature function
The goal is to build the function that outputs for every $t_i$ the curvature $k(t_i)$.

In [13]:
#----------------------
# discrete derivature
def curvature(t,f):
    # TO BE DONE
    return curvature_f # curvature_f is of size 1 x n

#---------------------
# check that function on simple examples



## 4) Evolute 
Define the evolute, namely the set of centers of curvatures. 

In [14]:
#----------------------
# discrete derivature
def evolute(t,f):
    # TO BE DONE
    return evolute_f # evolute_f is of size 3 x n



## PART II. 1) Evolute of the helicoid
Plot the evolute of the helicoid 
$$
\begin{array}{lllll}
\gamma :&\mathbb{R}&\to&\mathbb{R}^3\\ 
&t &\mapsto & (R\cos t, R \sin t, at).
\end{array}
$$

## 2) Evolute of the catenary
Plot the evolute of the catenary 
$$
\begin{array}{lllll}
\gamma :&\mathbb{R}&\to&\mathbb{R}^2\\ 
&t &\mapsto & (t,\cosh t).
\end{array}
$$

## 3) Evolute of Bezier curves
Plot the evolute of  Bezier curve that you created before.